// Guest list for Grace & Elmar's wedding RSVP.
// Edit this list to add or remove names; matching is accent-insensitive.
window.GUESTS = [
  "Aileen Lapus",
  "Alexandra Syquia",
  "Ana Medina",
  "Angelo Villaluz",
  "Anna Lissa Dueñas",
  "Apo Sesing",
  "Arnel Dela Cruz",
  "Arturo Fadriquela",
  "Arvey Oasay",
  "Ayen Lluvido",
  "Beloved Asco",
  "Celine Cultura",
  "Charlie Sobrevega",
  "Christopher Kevin Ocampo",
  "Clio Elizandre Villanueva",
  "Dexter Mallari",
  "Diego Garalde",
  "Dominic Gaspe",
  "Dyanna Valderrama",
  "Elizabeth Asco",
  "Elma Sobrevega",
  "Elmaz Sobrevega",
  "Elmer R. Susano",
  "Evelyn Panlilio",
  "Fides Marie L. Cunanan-Susano",
  "Franz Bravo",
  "Freddie Mallari",
  "Genesis Lluvido",
  "Gladys Panlilio",
  "Grace Avillanoza",
  "Helen Medina",
  "Ildefonso Quilloy",
  "Jack Mallari",
  "Jalen Lucero",
  "James Panlilio",
  "Jandrei Lucero",
  "Jenna Medina",
  "Jeremiah Andrew Esguerra",
  "Jeric Angeles",
  "Jocelyn Legaspi",
  "Joey Concepcion",
  "Johanne Isabel Dianalan",
  "Joseph Exequiel Susano",
  "Joshua Mallari",
  "Josielyn Mallari",
  "JR Fernandez",
  "Judy Ann Mallari",
  "Julia Cacho",
  "Julie Ann Ention",
  "Jumar Bravo",
  "Jun Bravo",
  "Juna Marie Bravo",
  "Justin Josef Callejo",
  "Justin Medina",
  "Krystel Francisco",
  "Kyrie Legaspi",
  "Lance Fadriquela",
  "Lia Andrea Pinaroc",
  "Liam Dianalan",
  "Lourde Almarza",
  "Ma. Bernardita Fadriquela",
  "Ma. Chrisanti Jubilee Boquiren",
  "Mack Fernandez",
  "Mahalia Fernandez",
  "Marieta Bravo",
  "Medz Lucero",
  "Mika Angeles",
  "Mike Gantuangco",
  "Miles Dimaano",
  "Miriam Fernandez",
  "Myla Dueñas",
  "Neil Aldrin Dela Cruz",
  "Noemi Quilloy",
  "Rangel Lapus",
  "Reymond G Lapus",
  "Rhoderick Fernandez",
  "Roma Kristian Gestiada",
  "Roman Maningo Jr.",
  "Romeo Fernandez",
  "Rosalinda Dela Cruz",
  "Rudy Fernandez",
  "Ryan Trangia",
  "SF04 Lecerio Dueñas",
  "Sophia Icasiano",
  "Toribio Asco",
  "Valerie Bico",
  "Valerie Jeseth Legaspi",
  "Victor Legaspi",
  "Vince Jerald Legaspi",
  "Von Legaspi",
  "Yoshiro Arai",
  "Yuichiro Arai",
  "Yumiko Arai",
  "Zaldy Sobrevega",
  "Zaldy Sobrevega Jr.",
];
