// Guest list for Grace & Elmar — used by the RSVP name lookup.
// Edit here to add, remove, or fix names: one per line, inside "quotes", comma-separated.
// Order doesn't matter, and accents (e.g. ñ) are matched even if typed as plain letters.
window.GUESTS = [
  "Aileen Lapus",
  "Alexandra Syquia",
  "Ana Medina",
  "Angelo Villaluz",
  "Anna Lissa Dueñas",
  "Apo Sesing",
  "Arnel Dela Cruz",
  "Arturo Fadriquela",
  "Arvey Oasay",
  "Ayen Lluvido",
  "Beloved Asco",
  "Celine Cultura",
  "Christopher Kevin Ocampo",
  "Clio Elizandre Villanueva",
  "Diego Garalde",
  "Dominic Gaspe",
  "Dyanna Valderrama",
  "Elizabeth Asco",
  "Elmaz Sobrevega",
  "Elmer R. Susano",
  "Evelyn Panlilio",
  "Fides Marie L. Cunanan-Susano",
  "Franz Bravo",
  "Freddie Mallari",
  "Genesis Lluvido",
  "Gladys Panlilio",
  "Grace Avillanoza",
  "Helen Medina",
  "Ildefonso Quilloy",
  "Jack Mallari",
  "Jalen Lucero",
  "James Panlilio",
  "Jandrei Lucero",
  "Jenna",
  "Jeremiah Andrew Esguerra",
  "Jeric Angeles",
  "Joey Concepcion",
  "Joseph Exequiel Susano",
  "Joshua Mallari",
  "Josielyn Mallari",
  "JR Fernandez",
  "Judy Ann Mallari",
  "Julia Cacho",
  "Julie Ann Ention",
  "Jumar Bravo",
  "Jun Bravo",
  "Juna Marie Bravo",
  "Justin Josef Callejo",
  "Justin Medina",
  "Kyrie Legaspi",
  "Lance Fadriquela",
  "Lia Andrea Pinaroc",
  "Ma. Bernardita Fadriquela",
  "Ma. Chrisanti Jubilee Boquiren",
  "Mack Fernandez",
  "Mahalia Fernandez",
  "Marieta Bravo",
  "Medz Lucero",
  "Mika Angeles",
  "Mike Gantuangco",
  "Miles Dimaano",
  "Miriam Fernandez",
  "Myla Dueñas",
  "Neil Aldrin Dela Cruz",
  "Noemi Quilloy",
  "Rangel Lapus",
  "Reymond G Lapus",
  "Rhoderick Fernandez",
  "Roma Kristian Gestiada",
  "Romeo Fernandez",
  "Rosalinda Dela Cruz",
  "Rudy Fernandez",
  "Ryan Trangia",
  "SF04 Lecerio Dueñas",
  "Sophia Icasiano",
  "Toribio Asco",
  "Valerie Bico",
  "Valerie Jeseth Legaspi",
  "Vince Jerald Legaspi",
  "Von Legaspi",
  "Yoshiro Arai",
  "Yuichiro Arai",
  "Yumiko Arai",
  "Zaldy Sobrevega Jr."
];
